name: Build WebRTC Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          echo "Preparing WebRTC build"
          uname -a
          df -h

      - name: Checkout WebRTC build scripts
        run: |
          git clone --branch m144.7559.14 --depth 1 \
            https://github.com/webrtc-sdk/webrtc-build.git webrtc-build

      - name: Check build scripts
        run: |
          ls -la webrtc-build
          ls -la webrtc-build/build
